# Site settings
title: Michel Moser
email: michel.moser@ips.unibe.ch
description: The Jekyll version of the Highlights theme by HTML5 UP.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://michelmoser.github.io" # the base hostname & protocol for your site

# Social settings
500px_url:
github_url: https://michelmoser.github.io
googleplus_url: https://plus.google.com/u/0/118084129488995392616
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/michel-moser-60311783/
twitter_url: https://twitter.com/michel_moser

# Build settings
markdown: kramdown
